# Neutron (Networking Service)
- name: install neutron
  apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
    state: present

- name: restart neutron-server service
  service:
    name: neutron-server
    state: restarted

- name: restart neutron-linuxbridge-agent service
  service:
    name: neutron-linuxbridge-agent
    state: restarted

- name: restart neutron-dhcp-agent service
  service:
    name: neutron-dhcp-agent
    state: restarted

- name: neutron-metadata-agent service
  service:
    name: neutron-metadata-agent
    state: restarted

# Horizon (Dashboard)
- name: install horizon
  apt:
    name: openstack-dashboard
    state: present

- name: restart apache2 service
  service:
    name: apache2
    state: restarted

# Cinder (Block Storage Service)
- name: install cinder
  apt:
    name:
      - cinder-api
      - cinder-scheduler
    state: present

- name: restart nova-api service
  service:
    name: nova-api
    state: restarted

- name: restart cinder-scheduler service
  service:
    name: cinder-scheduler
    state: restarted

- name: restart apache2 service
  service:
    name: apache2
    state: restarted
